version: "3.8"
services:
  web:
    build: .
    container_name: web-dev-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ../../packages:/packages
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_URL=postgresql://webdev:webdev123@db:5432/webdev
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:14.2
    container_name: web-dev-database
    environment:
      POSTGRES_PASSWORD: webdev123
      POSTGRES_USER: webdev
      POSTGRES_DB: webdev
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
