version: "3.8"
services:
  db:
    image: postgres:14.2
    container_name: web-dev-database
    environment:
      POSTGRES_PASSWORD: webdev123
      POSTGRES_USER: webdev
      POSTGRES_DB: webdev
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
