export const USER_AGENT =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.53'

export const APP_NAME = 'SERAPI'
export const ORIGIN = 'https://serapi-star.club'
export const API_ORIGIN = process.env.API_ORIGIN ?? 'http://localhost:3000'
export const areaGroupMap = new Map([
  ['北海道', 'hokkaido'],
  ['青森', 'tohoku'],
  ['岩手', 'tohoku'],
  ['宮城', 'tohoku'],
  ['秋田', 'tohoku'],
  ['山形', 'tohoku'],
  ['福島', 'tohoku'],
  ['東京', 'kanto'],
  ['神奈川', 'kanto'],
  ['千葉', 'kanto'],
  ['埼玉', 'kanto'],
  ['群馬', 'kanto'],
  ['茨城', 'kanto'],
  ['栃木', 'kanto'],
  ['愛知', 'chubu'],
  ['長野', 'chubu'],
  ['岐阜', 'chubu'],
  ['山梨', 'chubu'],
  ['新潟', 'chubu'],
  ['富山', 'chubu'],
  ['石川', 'chubu'],
  ['福井', 'chubu'],
  ['静岡', 'chubu'],
  ['大阪', 'kansai'],
  ['兵庫', 'kansai'],
  ['京都', 'kansai'],
  ['奈良', 'kansai'],
  ['和歌山', 'kansai'],
  ['三重', 'kansai'],
  ['滋賀', 'kansai'],
  ['岡山', 'chugoku-shikoku'],
  ['広島', 'chugoku-shikoku'],
  ['鳥取', 'chugoku-shikoku'],
  ['島根', 'chugoku-shikoku'],
  ['山口', 'chugoku-shikoku'],
  ['徳島', 'chugoku-shikoku'],
  ['香川', 'chugoku-shikoku'],
  ['愛媛', 'chugoku-shikoku'],
  ['高知', 'chugoku-shikoku'],
  ['福岡', 'kyusyu-okinawa'],
  ['長崎', 'kyusyu-okinawa'],
  ['佐賀', 'kyusyu-okinawa'],
  ['熊本', 'kyusyu-okinawa'],
  ['大分', 'kyusyu-okinawa'],
  ['宮崎', 'kyusyu-okinawa'],
  ['鹿児島', 'kyusyu-okinawa'],
  ['沖縄', 'kyusyu-okinawa'],
])
export const areaGroupNameMap = new Map([
  ['hokkaido', '北海道'],
  ['tohoku', '東北'],
  ['kanto', '関東'],
  ['chubu', '中部'],
  ['kansai', '関西'],
  ['chugoku-shikoku', '中国・四国'],
  ['kyusyu-okinawa', '九州・沖縄'],
])

export const presetUserIconMap = new Map([
  [1, 'https://assets.serapi-star.club/user-icons/preset-user-icon-1.webp'],
  [2, 'https://assets.serapi-star.club/user-icons/preset-user-icon-2.webp'],
  [3, 'https://assets.serapi-star.club/user-icons/preset-user-icon-3.webp'],
  [4, 'https://assets.serapi-star.club/user-icons/preset-user-icon-4.webp'],
  [5, 'https://assets.serapi-star.club/user-icons/preset-user-icon-5.webp'],
  [6, 'https://assets.serapi-star.club/user-icons/preset-user-icon-6.webp'],
  [7, 'https://assets.serapi-star.club/user-icons/preset-user-icon-7.webp'],
  [8, 'https://assets.serapi-star.club/user-icons/preset-user-icon-8.webp'],
])

export const areaNameTranslations = new Map<string, Record<string, string>>([
  [
    'ch',
    {
      北海道: '北海道',
      青森: '青森',
      岩手: '岩石',
      宮城: '皇宫',
      秋田: '秋田',
      山形: '山形',
      福島: '福岛',
      東京: '东京',
      神奈川: '神奈川',
      千葉: '千叶',
      埼玉: '埼玉',
      群馬: '群马县',
      茨城: '茨城',
      栃木: '枥木',
      愛知: '爱知',
      長野: '长野',
      岐阜: '岐阜',
      山梨: '榛',
      新潟: '新潟',
      富山: '富山',
      石川: '石川',
      福井: '福井',
      静岡: '静冈',
      大阪: '大阪',
      兵庫: '兵库',
      京都: '京都',
      奈良: '奈良',
      和歌山: '和歌山',
      三重: '三倍',
      滋賀: '滋贺',
      岡山: '冈山',
      広島: '广岛',
      鳥取: '家禽饲养',
      島根: '岛国',
      山口: '山口县',
      徳島: '德岛',
      香川: '香川',
      愛媛: '爱媛',
      高知: '高知',
      福岡: '福冈',
      長崎: '长崎',
      佐賀: '传奇',
      熊本: '熊本',
      大分: '相当',
      宮崎: '宫崎',
      鹿児島: '鹿儿岛',
      沖縄: '冲绳',
    },
  ],
])
